### ISSUE TITLE
Question on indexing and language highlighting.

### ISSUE THREAD

**Issue by biffbaff64** [4ch1m/kick-assembler-acbg#13]
How far along is the development of 6502 language highlighting and indexing?
For example, if I have a file called vic2chip.asm which contains a namespace, and that file is imported in my main,asm, which is my main file and all others are imported at the end of this file, and then in irq.asm i try to access that vic namespace, should the members of vic be shown to me?

**Comment by 4ch1m** [comment]
Both the [Flex](https://github.com/4ch1m/kick-assembler-acbg/blob/master/app/src/main/java/de/achimonline/kickassembler/acbg/lexer/KickAssembler.flex) and the [BNF](https://github.com/4ch1m/kick-assembler-acbg/blob/master/app/src/main/java/de/achimonline/kickassembler/acbg/psi/KickAssembler.bnf) definitions need major rework/improvements.

Any help/contribution is appreciated.

(Closing; since this is not really an "issue". Can still be used for discussion.)

**Comment by biffbaff64** [comment]
Ok great. It's not a major issue right now, and I'd be happy to take a look
