### ISSUE TITLE
Configure to Build and Run the prg from VICE

### ISSUE THREAD

**Issue by hayesmaker** [4ch1m/kick-assembler-acbg#3]
I've configured Vice as an external tool per the README, but cant see how to add an option to the buid config to to have the output PRG opened in vice from a Build & Run?

Is this possible, and how?

**Comment by 4ch1m** [comment]
That's fairly simple.
IntelliJ is a powerful friend. :smile:

You can chain multiple run-configurations together and have them executed in sequence.
However, IntelliJ only lets you choose existing/other run-configurations to run BEFORE launch (not after).

So you'll have think the other way 'round (and use some shell magic; if you happen to work on a *nix-system).

Three easy steps:

* Create your KickAssembler-run-configuration (which will compile your code and generate the PRG-file).
* Create a tiny shell-script (or batch-file on Windows) which will find and kill any currently running x64-emulator; determine the latest PRG-file; and run it with x64.
e.g.
``` 
#!/bin/bash
killall x64 &> /dev/null; x64 +confirmonexit $(ls -1t *.prg | head -n1)

``` 
* Now create a brand new ShellScript-run-configuration in IntelliJ and refer to the file created above. (Make sure your working directory is identical with the PRG-file's location!) And finally, add the run-configuration from the first step as "Before launch"-configuration.

Voila.
Now you have a one-click build'n'run.

I might add all of this to the README soon. :wink:

P.S.: While the "External Tool" might come in handy for quick usage via keyboard-shortcut; it unfortunately can't be used in the run-configuration itself since it's not possible to pass runconfig-specific arguments. At least not that I'm aware of.
